---
namespace: webfargo
name: check_point
version: 0.6.1
readme: README.md
authors:
  - Duane Toler <dtoler@webfargo.com>
description: >-
  Check Point Gaia OS automation modules for the Deployment Agent,
  facts gathering, and related operations.
license:
  - GPL-3.0-or-later
tags:
  - check_point
  - firewall
  - gaia
  - deployment
  - cpda
repository: "https://github.com/Webfargo/ansible-collection-check_point.git"
documentation: "https://github.com/Webfargo/ansible-collection-check_point/blob/main/README.md"
homepage: "https://github.com/Webfargo/ansible-collection-check_point.git"
issues: "https://github.com/Webfargo/ansible-collection-check_point/issues"
build_ignore:
  - "*.tar.gz"
  - ".git"
  - ".gitignore"
